### ISSUE TITLE
Wallets - Tracking issue for wallet management - Misc tasks

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/relayer-engine#110]
### Overview
This issue is for grouping tasks that relate to extending the core relayer functionality with various important or nice to have features in connection to relayer wallet management.

### Other tracking issues for the same effort:

- https://github.com/wormhole-foundation/relayer-engine/issues/109
- https://github.com/wormhole-foundation/relayer-engine/issues/108
- https://github.com/wormhole-foundation/relayer-engine/issues/107
- https://github.com/wormhole-foundation/relayer-engine/issues/106

### Breakdown
```[tasklist]
- [ ]
- [ ] Automated derived wallet creation based on load
- [ ] Support separated signing service to keep secret keys out of relayer engine
- [ ] Deal with common errors in blockchain specific rpc libraries (e.g. custom ethers provider)
- [ ] https://github.com/wormhole-foundation/relayer-engine/issues/124
```
